### PR TITLE
Added additional linting error keys.

### PR DESCRIPTION
**Pull request by dthagard**
This commit addresses the plugin warnings described here: https://github.com/uartois/sonar-golang/issues/12

### CODE REVIEW

**Comment by danielleberre** [comment]
Thanks for the PR.

Declaring the keys is one part of the job.

The second part is to declare the rules in an xml file with a textual description of the issue:
https://github.com/uartois/sonar-golang/blob/master/src/main/resources/rules/golint-rules.xml

To be able to accept the PR, we also need the corresponding part in the xml file.

The main issue is to find a nice description of the issue, with an example of code showing the problem and another one showing how to solve it.

**Comment by dthagard** [comment]
Ah, ok. Yes I see the `src/main/resources/rules/golint-rules.xml`. I'll spend some time digging into the docs on those linters and update the xml.

**Comment by thibaultfalque** [comment]
Hi,
Thanks for your PR. 
The third part is to declarre the rules in a properties file for active the rule in the default profile of the plugin. 
https://github.com/uartois/sonar-golang/blob/master/src/main/resources/profile.properties

Thanks again for your PR.

**Comment by dthagard** [comment]
The additional files have been updated to support the new linter warnings.

**Pull request merged**
